{% set name = "visdcc" %}
{% set version = "0.0.63" %}
{% set python_min = "3.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3c11b24f3a63060b90fa40b260aa7296329ae46f7239cff20daa1b4f753f3400

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - dash
    - dash-renderer
    - dash-html-components
    - dash-core-components

test:
  requires:
    - python {{ python_min }}
  imports:
    - dash
    - dash_core_components
    - dash_html_components
    - visdcc

about:
  home: https://github.com/jimmybow/visdcc
  license: MIT
  license_file: LICENSE.txt
  summary: Dash Core Components for Visualization.

extra:
  recipe-maintainers:
    - jfallmann
